services:
  db:
    image: supabase/postgres:15.1.0.145
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U supabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  rest:
    image: postgrest/postgrest:v12.0.2
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  auth:
    image: supabase/gotrue:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  storage:
    image: supabase/storage-api:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  kong:
    image: kong:3.4
    restart: always
    depends_on:
      rest: { condition: service_started }
      auth: { condition: service_started }
      storage: { condition: service_started }
    env_file: .env
    ports:
      - "8000:8000"
      - "8443:8443"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
