-- Tabela para guardar todos os eventos de visualização de página
CREATE TABLE public.page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  path TEXT NOT NULL,
  session_id UUID NOT NULL
);

-- Ativar Segurança a Nível de Linha (RLS)
ALTER TABLE public.page_views ENABLE ROW LEVEL SECURITY;

-- Política para permitir que qualquer visitante (anónimo ou não) insira um registo de visualização.
-- Isto é seguro porque eles não conseguem ler ou modificar os dados de outros.
CREATE POLICY "Allow public insert" ON public.page_views
  FOR INSERT
  WITH CHECK (TRUE);

-- Política para permitir que apenas administradores (você) possam ler todos os dados para as estatísticas.
CREATE POLICY "Allow admin read access" ON public.page_views
  FOR SELECT
  USING (auth.role() = 'service_role');


-- Tabela para guardar todos os eventos de clique em links de afiliados
CREATE TABLE public.affiliate_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  vpn_id BIGINT REFERENCES public.vpns(id) ON DELETE SET NULL, -- Usamos SET NULL para não perder o registo do clique se a VPN for apagada
  session_id UUID NOT NULL
);

-- Ativar Segurança a Nível de Linha (RLS)
ALTER TABLE public.affiliate_clicks ENABLE ROW LEVEL SECURITY;

-- Política para permitir que qualquer visitante insira um registo de clique.
CREATE POLICY "Allow public insert" ON public.affiliate_clicks
  FOR INSERT
  WITH CHECK (TRUE);

-- Política para permitir que apenas administradores (você) possam ler todos os dados.
CREATE POLICY "Allow admin read access" ON public.affiliate_clicks
  FOR SELECT
  USING (auth.role() = 'service_role');
